sudo: false
language: python
python:
  - 2.6
  - 2.7
# - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install argparse
  - pip install 'coverage>=4.0,<4.4'
  - pip install 'codeclimate-test-reporter'
script:
  - coverage run lld-glusterfs-fuse.py
after_success:
  - codeclimate-test-reporter
